import type { Metadata } from 'next';
import ViewFinderIcon from '@/assets/icons/viewfinder-circle';
import localFont from 'next/font/local';
import './globals.css';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Paloma Transaction Monitoring Tool',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className='flex justify-between bg-header w-full text-white px-3 py-4'>
          <ViewFinderIcon />
          <h1 className='inline-block text-white uppercase font-semibold'>Transaction Monitoring</h1>
          <div/>
        </header>
        {children}
      </body>
    </html>
  );
}
